name: make_my_trip
description: Flutter make my trip clone.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6595

  #notifacion
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.7.0
  
#  flutter_svg: ^1.0.0
  carousel_slider: ^4.1.1
  flutter_staggered_grid_view: ^0.6.2
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  flutter_phone_direct_caller: ^2.1.1
  flutter_email_sender: ^5.1.0
  share_plus: ^4.0.10
  image_downloader: ^0.31.0
  #utils
#  uuid: ^3.0.6
#  grouped_list: ^4.1.0
#  string_validator: ^0.3.0

  #api call
  dio: ^4.0.6

  #firebase services
  firebase_core: ^1.20.0
  firebase_auth: ^2.0.0
  google_sign_in: ^5.0.2
  flutter_facebook_auth: ^4.4.0
  firebase_storage: ^10.3.4
  cloud_firestore: ^3.4.1
  firebase_dynamic_links: ^4.3.3
  flutter_isolate:

  #state management :::use cubit pattern
  flutter_bloc: ^8.0.1

  #for state checking ::: use equatable or freezed package
  equatable: ^2.0.3

  #for routing use auto_route or go_route or any named routing
#  auto_route: ^3.2.1

  #error handling
  dartz: ^0.10.1

  #for reactive programming
  rxdart: ^0.27.4

  #dependency injection
  get_it: ^7.2.0

  #for dateTime conversions
  intl: ^0.17.0

  #for launcher icon
  flutter_launcher_icons: ^0.9.3

  #for checking internet connectivity
  connectivity_plus: ^2.3.5
  flutter_rating_bar: ^4.0.1
#  salomon_bottom_bar: ^3.3.1
  dots_indicator: ^2.1.0
  google_maps_flutter: ^2.1.8
  url_launcher: ^6.1.5

#  video_player: ^2.4.5
  scrollable_clean_calendar: ^1.4.0
  page_transition: ^2.0.9
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^10.1.0
#  device_info_plus: ^4.1.2
  platform_device_id: ^1.0.1
  razorpay_flutter: ^1.3.0
  flutter_html: ^2.2.1
  firebase_remote_config: ^2.0.15

  #shimmer effect

dev_dependencies:
  flutter_test:
    sdk: flutter

  #for lint checks
  flutter_lints: ^1.0.0

  #use this for testing
  mockito: 5.2.0
  build_runner: 2.1.11
  bloc_test: ^9.0.3

  #for generating launcher icon for android and ios
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_app_logo.png"
flutter:
  uses-material-design: true

  #your all local assets
  assets:
    - assets/icons/
    - assets/img/
    - assets/video/


  # font family of app
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
