name: make_my_trip
description: Flutter make my trip clone.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6595
  flutter_svg: ^1.0.0
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2

  #utils
  uuid: ^3.0.6
  grouped_list: ^4.1.0
  string_validator: ^0.3.0

  #api call
  dio: ^4.0.6

  #firebase services
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0

  #state management :::use cubit pattern
  flutter_bloc: ^8.0.1

  #for state checking ::: use equatable or freezed package
  equatable: ^2.0.3

  #for routing use auto_route or go_route or any named routing
  auto_route: ^3.2.1

  #error handling
  dartz: ^0.10.1

  #for reactive programming
  rxdart: ^0.27.4

  #dependency injection
  get_it: ^7.2.0

  #for dateTime conversions
  intl: ^0.17.0

  #for launcher icon
  flutter_launcher_icons: ^0.9.3

  #for checking internet connectivity
  connectivity_plus: ^2.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  #for lint checks
  flutter_lints: ^1.0.0

  #use this for testing
  mockito: 5.2.0
  build_runner: 2.1.11
  bloc_test: ^9.0.3


  #for generating launcher icon for android and ios
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_app_logo.png"
flutter:
  uses-material-design: true

  #your all local assets
  assets:
    - assets/icons/

  # font family of app
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

